# Generated by Django 2.2 on 2020-10-31 19:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20201028_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='social_avatar',
            field=models.CharField(blank=True, max_length=1024, verbose_name='аватар'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 2, 19, 27, 32, 120281, tzinfo=utc)),
        ),
    ]
